// Mocks generated by Mockito 5.4.4 from annotations
// in health_app/test/features/health_tracking/data/services/health_metrics_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:health_app/core/errors/failures.dart' as _i5;
import 'package:health_app/core/network/auth_helper.dart' as _i10;
import 'package:health_app/core/network/authentication_service.dart' as _i11;
import 'package:health_app/features/health_tracking/data/datasources/local/health_tracking_local_datasource.dart'
    as _i2;
import 'package:health_app/features/health_tracking/data/datasources/remote/health_tracking_remote_datasource.dart'
    as _i8;
import 'package:health_app/features/health_tracking/data/models/health_metric_model.dart'
    as _i9;
import 'package:health_app/features/health_tracking/domain/entities/health_metric.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HealthTrackingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthTrackingLocalDataSource extends _i1.Mock
    implements _i2.HealthTrackingLocalDataSource {
  MockHealthTrackingLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>> getHealthMetric(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHealthMetric,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.HealthMetric>>(
          this,
          Invocation.method(
            #getHealthMetric,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>
      getHealthMetricsByUserId(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getHealthMetricsByUserId,
              [userId],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>(
              this,
              Invocation.method(
                #getHealthMetricsByUserId,
                [userId],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>
      getHealthMetricsPaginated({
    required String? userId,
    required int? page,
    required int? pageSize,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getHealthMetricsPaginated,
              [],
              {
                #userId: userId,
                #page: page,
                #pageSize: pageSize,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>(
              this,
              Invocation.method(
                #getHealthMetricsPaginated,
                [],
                {
                  #userId: userId,
                  #page: page,
                  #pageSize: pageSize,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>
      getHealthMetricsByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getHealthMetricsByDateRange,
              [
                userId,
                startDate,
                endDate,
              ],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>(
              this,
              Invocation.method(
                #getHealthMetricsByDateRange,
                [
                  userId,
                  startDate,
                  endDate,
                ],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>> getHealthMetricByDate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHealthMetricByDate,
          [
            userId,
            date,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.HealthMetric>>(
          this,
          Invocation.method(
            #getHealthMetricByDate,
            [
              userId,
              date,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>> getLatestWeight(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestWeight,
          [userId],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.HealthMetric>>(
          this,
          Invocation.method(
            #getLatestWeight,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>> saveHealthMetric(
          _i6.HealthMetric? metric) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHealthMetric,
          [metric],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.HealthMetric>>(
          this,
          Invocation.method(
            #saveHealthMetric,
            [metric],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>> updateHealthMetric(
          _i6.HealthMetric? metric) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHealthMetric,
          [metric],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.HealthMetric>>(
          this,
          Invocation.method(
            #updateHealthMetric,
            [metric],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.HealthMetric>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteHealthMetric(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHealthMetric,
          [id],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteHealthMetric,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteHealthMetricsByUserId(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHealthMetricsByUserId,
          [userId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteHealthMetricsByUserId,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<
      _i4.Either<_i5.Failure, List<_i6.HealthMetric>>> saveHealthMetricsBatch(
          List<_i6.HealthMetric>? metrics) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHealthMetricsBatch,
          [metrics],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>(
          this,
          Invocation.method(
            #saveHealthMetricsBatch,
            [metrics],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> migrateMetricsToUserId({
    required String? fromUserId,
    required String? toUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateMetricsToUserId,
          [],
          {
            #fromUserId: fromUserId,
            #toUserId: toUserId,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
          this,
          Invocation.method(
            #migrateMetricsToUserId,
            [],
            {
              #fromUserId: fromUserId,
              #toUserId: toUserId,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>
      getAllHealthMetrics() => (super.noSuchMethod(
            Invocation.method(
              #getAllHealthMetrics,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>(
              this,
              Invocation.method(
                #getAllHealthMetrics,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.HealthMetric>>>);
}

/// A class which mocks [HealthTrackingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthTrackingRemoteDataSource extends _i1.Mock
    implements _i8.HealthTrackingRemoteDataSource {
  MockHealthTrackingRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
      _i4.Either<_i5.Failure, List<_i9.HealthMetricModel>>> getHealthMetrics({
    DateTime? startDate,
    DateTime? endDate,
    DateTime? updatedSince,
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHealthMetrics,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #updatedSince: updatedSince,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i9.HealthMetricModel>>>.value(
            _i7.dummyValue<
                _i4.Either<_i5.Failure, List<_i9.HealthMetricModel>>>(
          this,
          Invocation.method(
            #getHealthMetrics,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #updatedSince: updatedSince,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i9.HealthMetricModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.HealthMetricModel>> saveHealthMetric(
          _i9.HealthMetricModel? metric) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHealthMetric,
          [metric],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i9.HealthMetricModel>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i9.HealthMetricModel>>(
          this,
          Invocation.method(
            #saveHealthMetric,
            [metric],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i9.HealthMetricModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.HealthMetricModel>> updateHealthMetric(
          _i9.HealthMetricModel? metric) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHealthMetric,
          [metric],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i9.HealthMetricModel>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i9.HealthMetricModel>>(
          this,
          Invocation.method(
            #updateHealthMetric,
            [metric],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i9.HealthMetricModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteHealthMetric(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHealthMetric,
          [id],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteHealthMetric,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>> bulkSync(
          List<_i9.HealthMetricModel>? metrics) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkSync,
          [metrics],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, Map<String, dynamic>>>(
          this,
          Invocation.method(
            #bulkSync,
            [metrics],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [AuthHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthHelper extends _i1.Mock implements _i10.AuthHelper {
  MockAuthHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i11.AuthUser>> getProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i11.AuthUser>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i11.AuthUser>>(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i11.AuthUser>>);
}
